/*
  Sends MILES Resurrect Code sequence to IR LED.
  
  15 October 2016
  by Matt Geders
*/


int IRBlaster = 2;
// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(IRBlaster, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)

  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);

    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);

    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);

    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);

    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);

    digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(141);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(351);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(1653);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(309);
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(99);    
  digitalWrite(IRBlaster, HIGH);     
  delayMicroseconds(15);
  digitalWrite(IRBlaster, LOW);      
  delayMicroseconds(174);
  
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  //delay(5000);                       // wait for a second
}
